package cm:example;

interface kotlin {
    test: func() -> result<bool, s32>;
}

interface rust {
    test: func() -> result<bool, s32>;
}

world kotlin-default {
  import rust;
  export rust;
  export kotlin;
}
